# -*- coding: utf-8 -*-
"""mod signature synthetic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKjX8jcv7JFCIlux9fRFLYO6uvJMdUAQ
"""

import pandas as pd
import numpy as np
import json

"""
##############################################################################
5 is omitted because you know why!
But running this for other moduli please remove the if value%5 !=0
otherwise the signatures wont be meaningful and you know why!
##############################################################################
"""
mods = 30030

# Generate odd numbers from 1 to mods
odd_numbers = np.arange(1, mods, 2)

# Remove multiples of 5 from the odd numbers
odd_numbers = odd_numbers[odd_numbers % 5 != 0]

# Create the DataFrame with the product of row and column indices, modulo mods
df = pd.DataFrame(np.outer(odd_numbers, odd_numbers) % mods, index=odd_numbers, columns=odd_numbers)

# Step 1: Create the dictionary for all values, including 0
result_dict = {value: set() for value in odd_numbers if value%5 !=0}  # All odd numbers except multiples of 5
result_dict[0] = set() # Include key 0 please dont remove it serves an important function

# Step 2: Loop through the DataFrame to find all occurrences of each value
for row_index, row in df.iterrows():  # row_index is the row header
    for col_index, value in row.items():  # col_index is the column header
        if value in result_dict:
            # Add the (row_index + col_index) % 30030 to the dictionary for this value
            result_dict[value].add((row_index + col_index) % mods)

# Convert the sets to sorted lists for unique and ordered results
for key in result_dict:
    result_dict[key] = sorted(result_dict[key])

# Convert dictionary keys to standard `int` (or `str`) to make them serializable
result_dict = {int(key): value for key, value in result_dict.items()}

# Step 3: Print a small sample of the result_dict to verify
for key, value in list(result_dict.items())[:5]:  # First 5 items
    print(f"{key}: {value}")

# Step 4: Save the result as a Python-friendly JSON file
with open(f'/content/signature_{mods}.json', 'w') as json_file:
    json.dump(result_dict, json_file, indent=4)

# Step 5: Save the result as a plain text file
with open(f'/content/signature_{mods}.txt', 'w') as txt_file:
    txt_file.write(str(result_dict))

print("Files saved successfully!")

# Get the first and last key-value pairs
first_key, first_value = next(iter(result_dict.items()))  # Get the first key-value pair
last_key, last_value = list(result_dict.items())[-1]  # Get the last key-value pair

# Get the length of the first and last value (which are lists)
first_length = len(first_value)
last_length = len(last_value)

# Print the lengths
print(f"Length of the first item (key {first_key}): {first_length}")
print(f"Length of the last item (key {last_key}): {last_length}")

# Get the first and last key-value pairs
first_key, first_value = next(iter(result_dict.items()))  # Get the first key-value pair
last_key, last_value = list(result_dict.items())[-1]  # Get the last key-value pair

# Get the length of the first and last value (which are lists)
first_length = len(first_value)
last_length = len(last_value)

# Print the lengths
print(f"Length of the first item (key {first_key}): {first_length}")
print(f"Length of the last item (key {last_key}): {last_length}")

print(first_key, first_value)

import json

# Function to save dictionary in parts based on key ranges
def save_in_ranges(result_dict):
    # Part 1: Keys from 1 to 9999 (odd numbers)
    part_1_dict = {key: value for key, value in result_dict.items() if 1 <= key <= 9999 and key % 2 != 0}

    # Part 2: Keys from 10001 to 19999 (odd numbers)
    part_2_dict = {key: value for key, value in result_dict.items() if 10001 <= key <= 19999 and key % 2 != 0}

    # Part 3: Keys from 20001 to 30029 (odd numbers)
    part_3_dict = {key: value for key, value in result_dict.items() if 20001 <= key <= 30029 and key % 2 != 0}

    # Save the parts to separate files
    with open('/content/30030_mod_signature_part_1.txt', 'w') as txt_file:
        txt_file.write(str(part_1_dict))
    print("Part 1 saved: 1 to 9999")

    with open('/content/30030_mod_signature_part_2.txt', 'w') as txt_file:
        txt_file.write(str(part_2_dict))
    print("Part 2 saved: 10001 to 19999")

    with open('/content/30030_mod_signature_part_3.txt', 'w') as txt_file:
        txt_file.write(str(part_3_dict))
    print("Part 3 saved: 20001 to 30029")

# Example usage with your result_dict (replace with your actual dictionary)
save_in_ranges(result_dict)

# 1. Find the key with the maximum length of the value (list)
max_key = None
max_value_len = 0
for key, value in result_dict.items():
    if len(value) > max_value_len:
        max_value_len = len(value)
        max_key = key

# 2. Print the max length key and value
print(f"Max length key: {max_key}")
print(f"Max length value: {max_value_len}")

# 3. Count the number of keys in the dictionary
total_keys = len(result_dict)

# 4. Print the number of keys in the dictionary
print(f"Total number of keys in the dictionary: {total_keys}")

# 1. Find the key with the maximum length of the value (i.e., the largest list)
max_key = None
max_value_len = 0
for key, value in result_dict.items():
    if len(value) > max_value_len:  # Check if the length of the list is larger than the current max
        max_value_len = len(value)
        max_key = key

# 2. Print the max length key and its corresponding list length
print(f"Max length key: {max_key}")
print(f"Max length value: {max_value_len}")

# 3. Count the number of keys in the dictionary
total_keys = len(result_dict)

# 4. Print the total number of keys in the dictionary
print(f"Total number of keys in the dictionary: {total_keys}")

print(max_value_len)



# Iterate through the first 10 items of the dictionary
for key, value in list(result_dict.items())[:10]:
    print(f"Length of the list for key {key}: {len(value)}")

# Define the file path to save the key and length data
output_file_path = '/content/30030key_lengths.txt'

# Open the file in write mode
with open(output_file_path, 'w') as f:
    # Iterate through the dictionary
    for key, value in result_dict.items():
        # Write the key and the length of its value to the file, separated by a colon
        f.write(f"{key}: {len(value)}\n")

print(f"Key and length data saved to {output_file_path}")

import numpy as np
import matplotlib.pyplot as plt

# Get the lengths of all lists in the dictionary
list_lengths = [len(value) for value in result_dict.values()]

# Calculate key statistics
min_length = np.min(list_lengths)
max_length = np.max(list_lengths)
average_length = np.mean(list_lengths)
median_length = np.median(list_lengths)

print(f"Minimum length of lists: {min_length}")
print(f"Maximum length of lists: {max_length}")
print(f"Average length of lists: {average_length:.2f}")
print(f"Median length of lists: {median_length}")

# Plot the distribution of list lengths
plt.figure(figsize=(10, 6))
plt.hist(list_lengths, bins=50, edgecolor='black')
plt.title('Distribution of List Lengths in result_dict')
plt.xlabel('Length of Lists')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()



range_size = 100

# Find the maximum length to determine the upper bound for ranges
max_length = max(list_lengths)

# Create a dictionary to store the counts for each range
range_counts = {}

# Iterate through the list lengths and count occurrences in each range
for length in list_lengths:
    # Determine the lower bound of the range
    lower_bound = (length // range_size) * range_size
    # Define the range as a tuple (lower_bound, upper_bound)
    current_range = (lower_bound, lower_bound + range_size)

    # Increment the count for the corresponding range
    if current_range in range_counts:
        range_counts[current_range] += 1
    else:
        range_counts[current_range] = 1

# Sort the ranges for cleaner output
sorted_ranges = sorted(range_counts.keys())

# Define the output file path
output_file_path = '/content/range_counts.txt'

# Open the file in write mode
with open(output_file_path, 'w') as f:
    # Write the counts for each range to the file
    for current_range in sorted_ranges:
        lower, upper = current_range
        # Adjust the upper bound for the last range to include the max_length
        if upper > max_length and lower <= max_length:
            upper = max_length
            f.write(f"Length {lower}-{upper}: {range_counts[current_range]} values\n")
        elif upper <= max_length:
            f.write(f"Length {lower}-{upper}: {range_counts[current_range]} values\n")

print(f"Range counts saved to {output_file_path}")



import ast

# Define the file path
file_path = '/content/2310 signature.txt'

# Open and read the content of the file
with open(file_path, 'r') as f:
    file_content = f.read()

# Safely convert the string representation to a dictionary
loaded_dict = ast.literal_eval(file_content)

# Verify the type and a small sample of the loaded dictionary
print(type(loaded_dict))
for key, value in list(loaded_dict.items())[:5]:
    print(f"{key}: {value}")

# Create a list called list_lengths by iterating through the loaded_dict and getting the length of each value
list_lengths = [len(value) for value in loaded_dict.values()]

# Verify the first few elements and the length of the list_lengths list
print("First 10 elements of list_lengths:", list_lengths[:10])
print("Length of list_lengths:", len(list_lengths))

# Calculate key statistics
min_length = np.min(list_lengths)
max_length = np.max(list_lengths)
average_length = np.mean(list_lengths)
median_length = np.median(list_lengths)

# Print key statistics
print(f"Minimum length of lists: {min_length}")
print(f"Maximum length of lists: {max_length}")
print(f"Average length of lists: {average_length:.2f}")
print(f"Median length of lists: {median_length}")

# Define the range size
range_size = 30

# Find the maximum length to determine the upper bound for ranges
max_length = max(list_lengths)

# Create a dictionary to store the counts for each range
range_counts = {}

# Iterate through the list lengths and count occurrences in each range
for length in list_lengths:
    # Determine the lower bound of the range
    lower_bound = (length // range_size) * range_size
    # Define the range as a tuple (lower_bound, upper_bound)
    current_range = (lower_bound, lower_bound + range_size)

    # Increment the count for the corresponding range
    if current_range in range_counts:
        range_counts[current_range] += 1
    else:
        range_counts[current_range] = 1

# Sort the ranges for cleaner output
sorted_ranges = sorted(range_counts.keys())

# Define the output file path
output_file_path = '/content/range_counts_2310.txt'

# Open the file in write mode
with open(output_file_path, 'w') as f:
    # Write the counts for each range to the file
    for current_range in sorted_ranges:
        lower, upper = current_range
        # Adjust the upper bound for the last range to include the max_length
        if upper > max_length and lower <= max_length:
             # Check if the lower bound is within the max_length range
            if lower <= max_length:
                upper = max_length
                f.write(f"Length {lower}-{upper}: {range_counts[current_range]} values\n")
            else:
                 # Handle cases where the range starts beyond the max_length (shouldn't happen with integer division but as a safeguard)
                pass
        elif upper <= max_length:
            f.write(f"Length {lower}-{upper}: {range_counts[current_range]} values\n")


print(f"Range counts saved to {output_file_path}")

# Print key statistics (already calculated in a previous step)
print(f"Minimum length of lists: {min_length}")
print(f"Maximum length of lists: {max_length}")
print(f"Average length of lists: {average_length:.2f}")
print(f"Median length of lists: {median_length}")

# Define the file path for range counts
range_counts_file_path = '/content/range_counts_2310.txt'

# Read and print the content of the range counts file
print(f"\nDistribution of list lengths in ranges (from {range_counts_file_path}):")
try:
    with open(range_counts_file_path, 'r') as f:
        print(f.read())
except FileNotFoundError:
    print(f"Error: The file {range_counts_file_path} was not found.")